language: node_js
node_js: 
  - 13 
services: 
  - docker
install: 
 - echo "nothing needs to be installed"


script:
  - docker -version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag -t udagram-api-feed abanobmorgan/udagram-api-feed:v1
  - docker tag -t udagram-api-user abanobmorgan/udagram-api-user:v1
  - docker tag -t udagram-frontend abanobmorgan/udagram-frontend:v1
  - docker tag -t udagram-reverseproxy abanobmorgan/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  abanobmorgan/udagram-api-feed:v1
  - docker push  abanobmorgan/udagram-api-user:v1
  - docker push  abanobmorgan/udagram-frontend:v1
  - docker push  abanobmorgan/udagram-reverseproxy:v1
